#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\VarDumper\VarDumper;
use twobitint\AdventOfPHP\Runner;

function dd(...$vars) {
    if (array_key_exists(0, $vars) && 1 === count($vars)) {
        VarDumper::dump($vars[0]);
    } else {
        foreach ($vars as $k => $v) {
            VarDumper::dump($v, is_int($k) ? 1 + $k : $k);
        }
    }
    die;
}

$application = new Application();
$application->add(new Runner());
$application->setDefaultCommand('run', true);
$application->run();