#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use twobitint\AdventOfPHP\Runner;

$application = new Application();
$application->add(new Runner());
$application->setDefaultCommand('run', true);
$application->run();